/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tempconverter;

import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonModel;
import javax.swing.JRadioButton;
import javax.swing.SwingConstants;

/**
 *
 * @author Dan
 */
public class TempConverterFrame extends javax.swing.JFrame {

    /**
     * Creates new form TempConverter
     */
    public TempConverterFrame() {
        initComponents();
        rbCelsius.doClick();
        rbFahrenheit1.doClick();
        lblOutputMsg.setHorizontalAlignment(SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgInitialScale = new javax.swing.ButtonGroup();
        bgFinalScale = new javax.swing.ButtonGroup();
        lblTemperature = new javax.swing.JLabel();
        txtTemperature = new javax.swing.JTextField();
        lblDegrees = new javax.swing.JLabel();
        rbCelsius = new javax.swing.JRadioButton();
        rbFahrenheit = new javax.swing.JRadioButton();
        btnConvert = new javax.swing.JButton();
        lblOutputMsg = new javax.swing.JLabel();
        rbKelvin = new javax.swing.JRadioButton();
        rbCelsius1 = new javax.swing.JRadioButton();
        rbFahrenheit1 = new javax.swing.JRadioButton();
        rbKelvin1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temperature Converter");

        lblTemperature.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTemperature.setText("Temperature:");

        txtTemperature.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTemperature.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTemperature.setText("0");
        txtTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperatureActionPerformed(evt);
            }
        });

        lblDegrees.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDegrees.setText("°");

        bgInitialScale.add(rbCelsius);
        rbCelsius.setText("Celsius");

        bgInitialScale.add(rbFahrenheit);
        rbFahrenheit.setText("Fahrenheit");

        btnConvert.setText("Convert");
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });

        lblOutputMsg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblOutputMsg.setForeground(new java.awt.Color(0, 51, 255));

        bgInitialScale.add(rbKelvin);
        rbKelvin.setText("Kelvin");

        bgFinalScale.add(rbCelsius1);
        rbCelsius1.setText("Celsius");

        bgFinalScale.add(rbFahrenheit1);
        rbFahrenheit1.setText("Fahrenheit");

        bgFinalScale.add(rbKelvin1);
        rbKelvin1.setText("Kelvin");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FROM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblOutputMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbFahrenheit)
                                    .addComponent(rbCelsius)
                                    .addComponent(rbKelvin)
                                    .addComponent(jLabel1))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbCelsius1)
                                    .addComponent(rbFahrenheit1)
                                    .addComponent(rbKelvin1)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTemperature)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDegrees, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)))))
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnConvert)
                .addGap(175, 175, 175))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, rbCelsius, rbFahrenheit, rbKelvin});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, rbCelsius1, rbFahrenheit1, rbKelvin1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDegrees))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbCelsius)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbFahrenheit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbKelvin))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbCelsius1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbFahrenheit1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbKelvin1)))
                .addGap(18, 18, 18)
                .addComponent(btnConvert)
                .addGap(13, 13, 13)
                .addComponent(lblOutputMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblDegrees, lblTemperature, txtTemperature});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed
        
        TempScale original = TempScale.CELSIUS, target = TempScale.CELSIUS;
        String originalScale = "", targetScale = "";
        
        if (rbCelsius.isSelected()) {
            original = TempScale.CELSIUS;
        } else if (rbFahrenheit.isSelected()) {
            original = TempScale.FAHRENHEIT;
        } else if (rbKelvin.isSelected()) {
            original = TempScale.KELVIN;
        }
        originalScale = original.toString().substring(0, 1);
        
        if (rbCelsius1.isSelected()) {
            target = TempScale.CELSIUS;
        } else if (rbFahrenheit1.isSelected()) {
            target = TempScale.FAHRENHEIT;
        } else if (rbKelvin1.isSelected()) {
            target = TempScale.KELVIN;
        }
        targetScale = target.toString().substring(0, 1);
        
        TempConversionService tcs = new TempConversionService();
        TempConverter c2F, f2C, c2K, k2C, f2K, k2F, identity;
        
        c2F = new CelsiusToFahrenheitConverter();
        f2C = new FahrenheitToCelsiusConverter();
        c2K = new CelsiusToKelvinConverter();
        k2C = new KelvinToCelsiusConverter();
        f2K = new FahrenheitToKelvinConverter();
        k2F = new KelvinToFahrenheitConverter();
        identity = new IdentityConverter();
        
        if (original == TempScale.CELSIUS
                && target == TempScale.FAHRENHEIT) {
            tcs.setConverter(c2F);    
        } else if (original == TempScale.FAHRENHEIT
                && target == TempScale.CELSIUS) {
            tcs.setConverter(f2C);    
        } else if (original == TempScale.CELSIUS
                && target == TempScale.KELVIN) {
            tcs.setConverter(c2K);    
        } else if (original == TempScale.KELVIN
                && target == TempScale.CELSIUS) {
            tcs.setConverter(k2C);    
        } else if (original == TempScale.FAHRENHEIT
                && target == TempScale.KELVIN) {
            tcs.setConverter(f2K);    
        } else if (original == TempScale.KELVIN
                && target == TempScale.FAHRENHEIT) {
            tcs.setConverter(k2F);    
        } else if (original == target) {
            tcs.setConverter(identity);
        }
        
        double originalDegrees = Double.parseDouble(txtTemperature.getText());
        double targetDegrees = tcs.getConverted(originalDegrees);
        String text = String.format("%.1f°%s is %.1f°%s",
                originalDegrees, originalScale, 
                targetDegrees, targetScale
        );
        lblOutputMsg.setText(text);
        
    }//GEN-LAST:event_btnConvertActionPerformed

    private void txtTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperatureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperatureActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TempConverterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TempConverterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TempConverterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TempConverterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TempConverterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgFinalScale;
    private javax.swing.ButtonGroup bgInitialScale;
    private javax.swing.JButton btnConvert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblDegrees;
    private javax.swing.JLabel lblOutputMsg;
    private javax.swing.JLabel lblTemperature;
    private javax.swing.JRadioButton rbCelsius;
    private javax.swing.JRadioButton rbCelsius1;
    private javax.swing.JRadioButton rbFahrenheit;
    private javax.swing.JRadioButton rbFahrenheit1;
    private javax.swing.JRadioButton rbKelvin;
    private javax.swing.JRadioButton rbKelvin1;
    private javax.swing.JTextField txtTemperature;
    // End of variables declaration//GEN-END:variables
}
